package voidorm

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// GenerateGoTypes renders a Go file with model structs derived from the schema project.
func GenerateGoTypes(project *SchemaProject, opts TypegenOptions) string {
	pkg := sanitizePackageName(opts.Package)
	if pkg == "" {
		pkg = "voiddbgen"
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by void_go. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	needsTime := false
	for _, model := range project.Models {
		for _, field := range model.Schema.Fields {
			if field.Type == FieldDateTime {
				needsTime = true
				break
			}
		}
		if needsTime {
			break
		}
	}

	if needsTime {
		b.WriteString("import \"time\"\n\n")
	}

	b.WriteString("// VoidDBBlobRef mirrors Blob fields returned by the server.\n")
	b.WriteString("type VoidDBBlobRef struct {\n")
	b.WriteString("\tBucket       string            `json:\"_blob_bucket\"`\n")
	b.WriteString("\tKey          string            `json:\"_blob_key\"`\n")
	b.WriteString("\tURL          string            `json:\"_blob_url,omitempty\"`\n")
	b.WriteString("\tContentType  string            `json:\"content_type,omitempty\"`\n")
	b.WriteString("\tETag         string            `json:\"etag,omitempty\"`\n")
	b.WriteString("\tSize         int64             `json:\"size,omitempty\"`\n")
	b.WriteString("\tLastModified string            `json:\"last_modified,omitempty\"`\n")
	b.WriteString("\tMetadata     map[string]string `json:\"metadata,omitempty\"`\n")
	b.WriteString("}\n\n")

	models := append([]SchemaModel(nil), project.Models...)
	sort.Slice(models, func(i, j int) bool { return models[i].Name < models[j].Name })

	for _, model := range models {
		writeModelStruct(&b, model, false)
		writeCreateInputStruct(&b, model)
		writePatchInputStruct(&b, model)
	}

	formatted, err := format.Source([]byte(b.String()))
	if err == nil {
		return string(formatted)
	}
	return b.String()
}

func writeModelStruct(b *strings.Builder, model SchemaModel, includeAllPointers bool) {
	fmt.Fprintf(b, "// %s maps to %s/%s.\n", model.Name, model.Schema.Database, model.Schema.Collection)
	fmt.Fprintf(b, "type %s struct {\n", model.Name)
	for _, field := range model.Schema.Fields {
		goName := goFieldName(field)
		goType := goTypeForField(field, includeAllPointers)
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", goName, goType, jsonTag(field, !field.Required && !field.IsID))
	}
	b.WriteString("}\n\n")
}

func writeCreateInputStruct(b *strings.Builder, model SchemaModel) {
	fmt.Fprintf(b, "// %sCreateInput is the recommended insert payload type.\n", model.Name)
	fmt.Fprintf(b, "type %sCreateInput struct {\n", model.Name)
	for _, field := range model.Schema.Fields {
		if field.IsID {
			continue
		}
		goName := goFieldName(field)
		goType := goTypeForField(field, !field.Required)
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", goName, goType, jsonTag(field, !field.Required))
	}
	b.WriteString("}\n\n")
}

func writePatchInputStruct(b *strings.Builder, model SchemaModel) {
	fmt.Fprintf(b, "// %sPatchInput is the recommended patch payload type.\n", model.Name)
	fmt.Fprintf(b, "type %sPatchInput struct {\n", model.Name)
	for _, field := range model.Schema.Fields {
		if field.IsID {
			continue
		}
		goName := goFieldName(field)
		goType := goTypeForField(field, true)
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", goName, goType, jsonTag(field, true))
	}
	b.WriteString("}\n\n")
}

func goTypeForField(field SchemaField, pointerForScalar bool) string {
	var base string
	switch field.Type {
	case FieldString:
		base = "string"
	case FieldNumber:
		base = "float64"
	case FieldBoolean:
		base = "bool"
	case FieldDateTime:
		base = "time.Time"
	case FieldBlob:
		base = "VoidDBBlobRef"
	case FieldArray:
		base = "[]any"
	default:
		base = "map[string]any"
	}

	if field.List {
		return "[]" + strings.TrimPrefix(base, "[]")
	}
	if (!field.Required || pointerForScalar) && supportsPointer(base) {
		return "*" + base
	}
	return base
}

func supportsPointer(base string) bool {
	return !strings.HasPrefix(base, "[]") && !strings.HasPrefix(base, "map[")
}

func jsonTag(field SchemaField, omitempty bool) string {
	name := field.Name
	if field.MappedName != "" {
		name = field.MappedName
	}
	if field.IsID {
		name = "_id"
	}
	if omitempty {
		return name + ",omitempty"
	}
	return name
}

func goFieldName(field SchemaField) string {
	if field.IsID || field.Name == "_id" || field.MappedName == "_id" {
		return "ID"
	}
	return toPascal(field.Name)
}

func sanitizePackageName(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	var out strings.Builder
	for _, r := range value {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'):
			out.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			out.WriteRune(r + ('a' - 'A'))
		}
	}
	return out.String()
}
